#Properties Config file
#Wed May 6 08:33:10 UTC 2026
motd=leni anarquia
server-name=leni anarquia
server-port=19132
gamemode=0
max-players=50
spawn-protection=16
white-list=off
enable-query=on
enable-rcon=off
announce-player-achievements=on
allow-flight=off
spawn-animals=on
spawn-mobs=on
force-gamemode=off
hardcore=off
pvp=on
difficulty=1
generator-settings=
level-name=world
level-seed=
level-type=DEFAULT
rcon.password=uQYbPshAC1
auto-save=on
view-distance=8
xbox-auth=off
show-coordinates=on
